version: '3'

services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/HobbyTown
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app worker --loglevel=info
    volumes:
      - .:/HobbyTown
    links:
      - redis
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app flower
    volumes:
      - .:/HobbyTown
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"
