# Generated by Django 5.0.3 on 2024-03-08 09:51

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название события')),
                ('image', models.ImageField(upload_to='static/media/%Y/%m/%d/', verbose_name='Картинка события')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('places', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(verbose_name='Дата конца')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('address', models.CharField(max_length=255, verbose_name='Место провождения')),
            ],
            options={
                'verbose_name': 'Игротека',
                'verbose_name_plural': 'Игротеки',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя настольной игры')),
                ('desc', models.TextField(verbose_name='Описание игры')),
                ('players_min', models.PositiveIntegerField(verbose_name='Минимальное количество игроков на игру')),
                ('players_max', models.PositiveIntegerField(verbose_name='Максимальное количество игроков на игру')),
            ],
            options={
                'verbose_name': 'Настолка',
                'verbose_name_plural': 'Настолки',
            },
        ),
        migrations.CreateModel(
            name='EventGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.PositiveIntegerField(verbose_name='Количество человек')),
                ('current', models.PositiveIntegerField(verbose_name='Количество записей')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobby.event', verbose_name='Игротека')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobby.game', verbose_name='Настолка')),
            ],
            options={
                'verbose_name': 'Игра на игротеку',
                'verbose_name_plural': 'Игры на игротеки',
            },
        ),
        migrations.CreateModel(
            name='RegularSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя записи')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KZ', verbose_name='Номер записи')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobby.event', verbose_name='Игрокета')),
            ],
            options={
                'verbose_name': 'Запись на игротеку',
                'verbose_name_plural': 'Записи на игротеки',
            },
        ),
        migrations.CreateModel(
            name='SpecialSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя записи')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KZ', verbose_name='Номер записи')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobby.event', verbose_name='Игрокета')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobby.eventgame', verbose_name='Игра на игротеке')),
            ],
            options={
                'verbose_name': 'Запись на игротеку + игру',
                'verbose_name_plural': 'Записи на игротеки + игры',
            },
        ),
    ]
