# Generated by Django 5.0.3 on 2024-03-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default=1, upload_to='static/media/%Y/%m/%d/', verbose_name='Картинка настолки'),
            preserve_default=False,
        ),
    ]
